### ISSUE TITLE
Slices: add an API like `Map` but do NOT return `nil` with 0-length slice 

### ISSUE THREAD

**Issue by Luffbee** [bobg/go-generics#10]
It will be good to support an API like `MapNonNil` which will return an empty slices instead of `nil`. The `nil` slice may be unexpected in some scenarios like json API, where `nil` is a different type than an array.

**Comment by bobg** [comment]
By this reasoning, we'd need `NonNil` variants of a lot of functions, which would bloat the API with redundancy - unnecessarily, in light of the alternative, which is to create an orthogonal `NonNil` function that can be used wherever there might be a `nil` slice where you don't want one.
