### ISSUE TITLE
`set` `Iter` method is expensive for large sets

### ISSUE THREAD

**Issue by rickb777** [bobg/go-generics#19]
Because the `set` `Iter` method copies the keys into a slice, it will perform poorly for large sets, requiring a larger memory footprint and taking time to make the copy.

It may be possible to have a rangeable sequence generator that 'eats' the input set by using `range` to take one value at a time, immediately delete that value from the set, and return that value via the `Val() T` method. This would trade off the reduction in memory footprint against the need to drain the set to empty. In some cases, this might be preferable.

The method providing this behaviour might be called `LazyIter` to indicate its difference from the existing `Iter` method.

**Comment by rickb777** [comment]
The documentation for the `Iter` method ought to be augmented to point out that the keys are copied and there is a cost to this.

**Comment by rickb777** [comment]
Ideally, the `Iter` method would not be present on `set.Of` instances. The `Slices` method provides an alternative for which the copy operation is more obvious.

**Comment by bobg** [comment]
This is a great point, thank you! I've added commentary about this in https://github.com/bobg/go-generics/pull/20.

As you may know, Go 1.23, which arrives in a few weeks, will include a major new feature, "[range over function](https://tip.golang.org/doc/go1.23#language)," that will make this module's `iter` package obsolete. I'm preparing a successor right now in anticipation. In the new package, the `set.Of.Iter` method is renamed to `All` (in keeping with a new convention for container types) and, as you can see [here](https://github.com/bobg/go-generics/blob/2b83b0666c44af437b7e58c978e2cde87f4d7d76/set/set.go#L98-L103), is implemented in a much more efficient manner (to wit, via `for range` as you suggested).

**Comment by bobg** [comment]
Addressed in #20.
