### ISSUE TITLE
Add slices.Any, slices.None

### ISSUE THREAD

**Issue by cloudshiftchris** [bobg/go-generics#2]
Any and None are useful constructs to determine if any (or none) of the elements match a predicate.

Sample implementations:

```

func Any[T any](ss []T, test func(T) bool) bool {
	for _, s := range ss {
		if test(s) {
			return true
		}
	}
	return false
}

func None[T any](ss []T, test func(T) bool) bool {
	for _, s := range ss {
		if test(s) {
			return false
		}
	}
	return true
}

```

**Comment by bobg** [comment]
Thank you for this suggestion.

As presented here, the functions seem too special-purpose to be in keeping with the other features of this module. A more general approach would allow you to, say, find the index of the first value that passes the test. It could return -1 if no such value is found. This allows the trivial implementation of `Any` and `None` and plenty of other functions besides.

```go
func Any[T any](s []T, test func(T) bool) bool {
  return indexOf(s, test) >= 0
}

func None[T any](s []T, test func(T) bool) bool {
  return !Any(s, test)
}

func All[T any](s []T, test func(T) bool) bool {
  notTest := func(val T) bool { return !test(val) }
  return !Any(s, notTest)
}
```

As it happens, I am presently updating the go-generics module to align with the planned inclusion, in Go 1.21, of new `slices` and `maps` packages in the standard library. See https://github.com/golang/go/issues/57433 and https://github.com/golang/go/issues/57436. The idea is for my `slices` and `maps` to be drop-in replacements for the stdlib versions, with enhancements. And the stdlib `slices` package will include [IndexFunc](https://pkg.go.dev/golang.org/x/exp/slices#IndexFunc), which behaves in exactly the way I illustrated above with `indexOf`.

Sound OK?

**Comment by bobg** [comment]
(In fact, [slices.ContainsFunc](https://pkg.go.dev/golang.org/x/exp/slices#ContainsFunc) is exactly your `Any`.)

**Comment by cloudshiftchris** [comment]
Sounds good.  Thanks for sharing the broader context.
