### ISSUE TITLE
Can't install v2.1.1

### ISSUE THREAD

**Issue by ezk84** [bobg/go-generics#6]
Thanks for the work :)

Can't seem to install the v2 version.

```bash
$ go get github.com/bobg/go-generics/slices
go: downloading github.com/bobg/go-generics v1.7.2
go: added github.com/bobg/go-generics v1.7.2
```

```bash
$ go get github.com/bobg/go-generics/slices@v2.1.1
go: github.com/bobg/go-generics/slices@v2.1.1: invalid version: unknown revision slices/v2.1.1
```

```bash
$ go get github.com/bobg/go-generics/slices/v2
go: module github.com/bobg/go-generics@upgrade found (v1.7.2), but does not contain package github.com/bobg/go-generics/slices/v2
```

**Comment by ezk84** [comment]
I was doing it wrong

```bash
$ go get github.com/bobg/go-generics/v2
go: downloading github.com/bobg/go-generics/v2 v2.2.0
go: added github.com/bobg/go-generics/v2 v2.2.0
```

**Comment by bobg** [comment]
Right!

It's important to understand the difference between _modules_ and _packages._ A module contains one or more packages. The major version suffix comes at the end of the module path; in this case `github.com/bobg/go-generics/v2`. Any contained subpackages, such as `slices`, get appended to the end. See https://go.dev/ref/mod#major-version-suffixes

Note, you _can_ specify a package path to `go get` like this:

```sh
$ go get github.com/bobg/go-generics/v2/slices
```

but what you'll end up getting is the whole module (`github.com/bobg/go-generics/v2`); see https://go.dev/ref/mod#resolve-pkg-mod
